# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 103741005+pr147@users.noreply.github.com
author_name: PB
cloud_provider: none
preset_name: production
project_name: LightningMcqueenEra

